includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser-full.yaml

variables:
  binary_name: markscribe
  description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
  github_url: "https://github.com/charmbracelet/markscribe"
  maintainer: "Ayman Bagabas <ayman@charm.sh>"
  brew_commit_author_name: "Ayman Bagabas"
  brew_commit_author_email: "ayman@charm.sh"
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
